"""add workflow_id to generation_tasks

Revision ID: 36b2b8e9161f
Revises: a83ec3548e76
Create Date: 2026-06-21 23:14:25.634322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b2b8e9161f'
down_revision: Union[str, None] = 'a83ec3548e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_generation_tasks_workflow_id'), ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_tasks_workflow_id'))
        batch_op.drop_column('workflow_id')

    # ### end Alembic commands ###
