"""add generation_task_id to generated_files

Revision ID: 70c6c3675292
Revises: ddf5113c762c
Create Date: 2026-06-22 00:16:55.877029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c6c3675292'
down_revision: Union[str, None] = 'ddf5113c762c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation_task_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_generated_files_generation_task_id'), ['generation_task_id'], unique=False)
        batch_op.create_foreign_key('fk_generated_files_generation_task_id', 'generation_tasks', ['generation_task_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_files', schema=None) as batch_op:
        batch_op.drop_constraint('fk_generated_files_generation_task_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_generated_files_generation_task_id'))
        batch_op.drop_column('generation_task_id')

    # ### end Alembic commands ###
